### ISSUE TITLE
I've made the translation of your site to brazilian portuguese

### ISSUE THREAD

**Issue by gabe-oliveira** [DanWin/main-website#3]
Hi Daniel!
I translated your personal website into Brazilian Portuguese.
Can I make a pull request to upload the files? I did the translation using the Poedit app.
My github is kinda new so I'm looking forward to adding it on Github and having my first contribution to third party projects.

**Comment by DanWin** [comment]
Hello @gabe-oliveira ,
great, thanks for the translation!
You can open a pull request and place your tranlslated file under `locale/pt_BR/LC_MESSAGES/main-website.po`
For the file to be picked up, the new language needs to be added in [common.php](https://github.com/DanWin/main-website/blob/main/common.php#L58 ), but I can also do that when merging your pull request.

**Comment by DanWin** [comment]
Thanks again, I've merged the pull request and added it to the language menu.
