### ISSUE TITLE
Can't connect.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [DanWin/main-website#5]
![image](https://github.com/DanWin/main-website/assets/42837531/94c6637e-a63d-4066-ae5e-f379a08d7c6e)

<details>

<blockquote>

Secure Connection Failed

An error occurred during a connection to danwin1210.de. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.

[Learn more…](https://support.mozilla.org/1/firefox/113.0.1/Linux/en-GB/connection-not-secure)

</blockquote>

</details>

When visiting https://danwin1210.de/

**Comment by DanWin** [comment]
The website is back up and running and the cluster file system restored. Some file permissions still need to be updated, I've also just started the email server on the first node. Full functionality should be restored soon.
